version: '3.9'
services:
  mongodb:
    image: mongo:4-bionic
    volumes:
      - ./auth/data:/data/db
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile.dev
    environment:
      JWT_SECRET: secret
      MONGODB_URL: mongodb://mongodb/prodev-composed-auth
      NODE_ENV: development
    volumes:
      - ./auth/src:/usr/src/app/src
    depends_on:
      - mongodb
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./app/data:/usr/src/app/data
      - ./app/src:/usr/src/app/src
  ghi:
    build: ./ghi
    volumes:
      - ./ghi/static:/usr/share/nginx/html
    ports:
      - 8910:80
    depends_on:
      - app
      - auth