version: '3.9'
services:
  mongodb:
    image: mongo:4-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - ./auth/data:/data/db
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile.dev
    environment:
      JWT_SECRET: root
      MONGODB_URL: mongodb://mongo:27017
    depends_on:
      - mongodb
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./app/data:/usr/src/app/data
      - ./app/src:/usr/src/app/src
    depends_on:
      - auth
  ghi:
    image: nginx:1.19-alpine
    volumes:
      - ./ghi/static:/usr/share/nginx/html
    ports:
      - 8910:80
    depends_on:
      - app